spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/demo_order_0?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
        username: root
        password: ${MYSQL_USER:root}
        max-active: 16
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/demo_order_1?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
        username: root
        password: root
        max-active: 16
    sharding:
      tables:
#        tb_user_info:
#          actual-data-nodes: ${db.one}.tb_user_info_$->{0..1}
#          table-strategy:
#            inline:
#              sharding-column: create_date
#              algorithm-expression: tb_user_info_$->{create_date%2}
#          key-generator:
#            column: id
#            type: SNOWFLAKE $->{0..1}.
        t_order:
          actual-data-nodes: ds$->{0..1}.t_order_$->{0..1}
          database-strategy:
            standard:
              sharding-column: order_id
              precise-algorithm-class-name: com.lgh.demo.shardingdatabasetable.config.DbPreciseShardingAlgorithm
          table-strategy:
            standard:
              sharding-column: order_id
              precise-algorithm-class-name: com.lgh.demo.shardingdatabasetable.config.TablePreciseShardingAlgorithm
        t_order_item:
          actual-data-nodes: ds$->{0..1}.t_order_item_$->{0..1}
          database-strategy:
            standard:
              sharding-column: order_id
              precise-algorithm-class-name: com.lgh.demo.shardingdatabasetable.config.DbPreciseShardingAlgorithm
          table-strategy:
            standard:
              sharding-column: order_id
              precise-algorithm-class-name: com.lgh.demo.shardingdatabasetable.config.TablePreciseShardingAlgorithm
        t_goods:
          actual-data-nodes: ds0.t_goods_$->{0..1}
#          database-strategy:
#            standard:
#              sharding-column: id
#              precise-algorithm-class-name: com.lgh.demo.shardingdatabasetable.config.DbPreciseShardingAlgorithm
          table-strategy:
            standard:
              sharding-column: id
              precise-algorithm-class-name: com.lgh.demo.shardingdatabasetable.config.TablePreciseShardingAlgorithm
      default-data-source-name: ds0
      binding-tables:
#       绑定表 规则主子表关系，联表查询防止出现笛卡尔积现象
#       绑定表： 指分片规则一致的主表和子表。
#         例如：t_order表和t_order_item表，均按照order_id分片(分片字段数据库名称需相同)，则此两张表互为绑定表关系。
#         绑定表之间的多表关联查询不会出现笛卡尔积关联，关联查询效率将大大提升。
        - t_order,t_order_item
#      广播表，在每个库里面都会存在，不分表
      broadcast-tables:
        - t_area
        - t_goods_type
    props:
      sql.show: true
#      default-database-strategy:
#        standard:
#          sharding-column:
#          precise-algorithm-class-name:

