spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_order_2?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


